apiVersion: batch/v1
kind: Job
metadata:
  name: malloc
spec:
  backoffLimit: 3
  parallelism: 3
  template:
    metadata:
      labels:
        app: malloc
    spec:
      restartPolicy: Never
      containers:
      - name: malloc
        image: reg.liarlee.site/library/sigsegv:latest
        resources:
          requests:
            cpu: 0.25
            memory: 101Mi
          limits:
            cpu: 0.25
            memory: 101Mi
